---
title: "Cleaning and Analyzing Student's student time using Janitor and tabyls"
author: "Corbin Cerny, Juan Quinones"
date: '10-28-2024'
output: 
 html_document:
    toc: TRUE
    df_print: paged
    number_sections: FALSE
    highlight: monochrome
    theme: yeti
    toc_depth: 3
    toc_float: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

## Introduction 
One big step for Data Scientists is to clean their data. Janitor is a library that allow examining and cleaning of data. In the following tutorial we are going to dive in some of Janitor functionalities to test its usability.

## Installing and Importing Janytor´s libraries


```{r}
#install.packages("janitor") #Uncomment this line in case you need to install the library.
#install.packages("readxl") 

library(janitor)
library(readxl)
library(dplyr)
```

#Data Set


```{r}
#Loading the data:
data <- read.csv("Data/student_sleep_patterns_mod.csv")

```

```{r}
#First we clean the names using janitor clean names function
data = data %>%
  clean_names()

data
```

```{r}
#We count how many null values we have
missing_values <- colSums(is.na(data))

# Display columns with missing values
missing_values[missing_values > 0]
```

```{r}
#We eliminate the rows that have null values
cleaned_data = remove_empty(data)
cleaned_data
```
```{r}
#We count how many null values we have
missing_values2 = colSums(is.na(cleaned_data))
missing_values2
```

```{r}
cleaned_data
```

```{r}
#Now we adorn the decimal columns
rounded_data <- adorn_rounding(cleaned_data, digits = 0)
rounded_data
```

```{r}
duplicate_columns <- rounded_data %>%
  get_dupes() 

duplicate_columns

```

```{r}
adorned_data2 <- rounded_data %>%
  distinct()

duplicate_columns <- adorned_data2 %>%
  get_dupes()

nrow(duplicate_columns)
```
```{r}
#First Row
tabyl(adorned_data2$university_year)
```
```{r}
#Second row
gender_year_tab = tabyl(adorned_data2, gender, university_year,  show_missing_levels = FALSE)

gender_year_tab_percent <- gender_year_tab %>%
  adorn_percentages("row") %>%   # Calculate percentages for each row
  adorn_pct_formatting()          # Format percentages nicely (e.g., 33% instead of 0.33)

#View the percentages
print(gender_year_tab_percent)
```
```{r}
#third row
tabyl(adorned_data2, university_year, age, gender, show_missing_levels = FALSE)

```

